# Generated by Django 6.0.6 on 2026-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('logo', models.ImageField(upload_to='teams/%y/%m/%d/')),
                ('founded', models.IntegerField()),
            ],
        ),
    ]
