# Generated by Django 6.0.6 on 2026-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('pL teams', 'pL teams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
