# Generated by Django 6.0.6 on 2026-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_category_alter_team_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('pL teams', 'pL teams'), ('La Liga teams', 'La Liga teams')], max_length=50, null=True),
        ),
    ]
