# Generated by Django 6.0.6 on 2026-06-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_date_alter_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
