# Generated by Django 6.0.6 on 2026-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
