# Generated by Django 6.0.6 on 2026-06-21 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
