# Generated by Django 6.0.6 on 2026-06-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
