# Generated by Django 6.0.6 on 2026-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('Premier League teams', 'Premier League teams'), ('La Liga teams', 'La Liga teams')], max_length=50, null=True),
        ),
    ]
