# Generated by Django 6.0.6 on 2026-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='team',
            new_name='teams',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='capacity',
        ),
        migrations.AddField(
            model_name='stadium',
            name='stadium',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
