# Generated by Django 6.0.6 on 2026-06-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_team_stadium_teams_rename_name_team_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='Teams',
        ),
    ]
