# Generated by Django 6.0.6 on 2026-06-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_team_team_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Teams',
            new_name='team',
        ),
    ]
