# Generated by Django 6.0.6 on 2026-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_match_date_match_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
