# Generated by Django 6.0.6 on 2026-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
