# Generated by Django 6.0.6 on 2026-07-24 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_newsarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanTeamOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_code', models.CharField(max_length=10)),
                ('matchday', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league_code', 'matchday')},
            },
        ),
        migrations.CreateModel(
            name='FanTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=150)),
                ('team_name', models.CharField(max_length=150)),
                ('team_logo', models.URLField(blank=True, null=True)),
                ('position_group', models.CharField(max_length=50)),
                ('fan_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pages.fanteamofweek')),
            ],
        ),
    ]
