# Generated by Django 6.0.6 on 2026-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_prediction_points_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status_code', models.IntegerField(default=200)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visited_at'], name='pages_pagev_visited_b0739c_idx'), models.Index(fields=['path'], name='pages_pagev_path_69a9f3_idx')],
            },
        ),
    ]
