# Generated by Django 6.0.6 on 2026-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='team_id',
            field=models.IntegerField(blank=True, help_text='رقم الفريق من API (مثلاً 33 لمانشستر يونايتد). اتركه فاضي لو الخبر عام أو خاص بالدوري فقط', null=True),
        ),
    ]
